'use client';
import { FormEvent, useState } from 'react';
import { X } from 'lucide-react';
import { useAppData } from './app-provider';
import { ClientStatus, ContractStatus, PaymentStatus } from '@/lib/types';

function Modal({title,close,children}:{title:string;close:()=>void;children:React.ReactNode}){return <div className="modal-backdrop"><div className="modal"><div className="modal-head"><h2>{title}</h2><button className="icon-btn" onClick={close}><X size={18}/></button></div>{children}</div></div>}
export function AddClientDialog({close}:{close:()=>void}){const {addClient}=useAppData();const [error,setError]=useState('');function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const name=String(f.get('name')||'').trim(),business=String(f.get('business')||'').trim();if(!name||!business){setError('Client name and business name are required.');return}addClient({id:`c${Date.now()}`,name,business,email:String(f.get('email')||''),phone:String(f.get('phone')||''),website:String(f.get('website')||''),status:String(f.get('status')) as ClientStatus,startDate:String(f.get('startDate')||''),launchDate:'',package:String(f.get('package')||''),projectValue:Number(f.get('projectValue')||0),recurringFee:Number(f.get('recurringFee')||0),notes:''});close()}return <Modal title="Add Client" close={close}><form onSubmit={submit}><div className="form-grid"><label>Name<input name="name"/></label><label>Business<input name="business"/></label><label>Email<input name="email" type="email"/></label><label>Phone<input name="phone"/></label><label>Website<input name="website"/></label><label>Status<select name="status" defaultValue="Lead"><option>Lead</option><option>Demo</option><option>Contract Signed</option><option>Building</option><option>Completed</option><option>Maintenance</option></select></label><label>Start date<input name="startDate" type="date"/></label><label>Package<input name="package" placeholder="5-page website"/></label><label>Project value<input name="projectValue" type="number" min="0"/></label><label>Recurring fee<input name="recurringFee" type="number" min="0"/></label></div>{error&&<div className="error">{error}</div>}<div className="form-actions"><button type="button" className="btn ghost" onClick={close}>Cancel</button><button className="btn accent">Add Client</button></div></form></Modal>}
export function CreateInvoiceDialog({close}:{close:()=>void}){const {clients,addPayment}=useAppData();const [error,setError]=useState('');function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const amount=Number(f.get('amount')||0);if(amount<=0){setError('Amount must be greater than $0.');return}addPayment({id:`pay${Date.now()}`,clientId:String(f.get('clientId')),invoice:String(f.get('invoice')||`INV-${Date.now()}`),type:String(f.get('type')) as 'Website'|'Hosting'|'Maintenance'|'Domain'|'Other',amountCharged:amount,amountPaid:0,paymentDate:'',dueDate:String(f.get('dueDate')||''),method:'',status:String(f.get('status')) as PaymentStatus});close()}return <Modal title="Create Invoice" close={close}><form onSubmit={submit}><div className="form-grid"><label>Client<select name="clientId">{clients.map(c=><option key={c.id} value={c.id}>{c.business}</option>)}</select></label><label>Invoice #<input name="invoice" placeholder="INV-1006"/></label><label>Type<select name="type"><option>Website</option><option>Hosting</option><option>Maintenance</option><option>Domain</option><option>Other</option></select></label><label>Amount<input name="amount" type="number" min="0" step="0.01"/></label><label>Due date<input name="dueDate" type="date"/></label><label>Status<select name="status"><option>Unpaid</option><option>Partial</option><option>Overdue</option><option>Paid</option></select></label></div>{error&&<div className="error">{error}</div>}<div className="form-actions"><button type="button" className="btn ghost" onClick={close}>Cancel</button><button className="btn accent">Create Invoice</button></div></form></Modal>}
export function UploadContractDialog({close}:{close:()=>void}){const {clients,addContract}=useAppData();function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);addContract({id:`ct${Date.now()}`,clientId:String(f.get('clientId')),name:String(f.get('name')||'Website Agreement'),signedDate:String(f.get('signedDate')||''),status:String(f.get('status')) as ContractStatus,fileName:String(f.get('fileName')||'contract.pdf')});close()}return <Modal title="Upload Contract" close={close}><form onSubmit={submit}><div className="form-grid"><label>Client<select name="clientId">{clients.map(c=><option key={c.id} value={c.id}>{c.business}</option>)}</select></label><label>Contract name<input name="name" defaultValue="Website Scope Agreement"/></label><label>Signed date<input name="signedDate" type="date"/></label><label>Status<select name="status"><option>Draft</option><option>Sent</option><option>Signed</option></select></label><label className="full">File name<input name="fileName" placeholder="client-contract.pdf"/></label></div><div className="muted" style={{fontSize:12,marginTop:10}}>Version 1 stores file metadata only. Real file storage will be connected later.</div><div className="form-actions"><button type="button" className="btn ghost" onClick={close}>Cancel</button><button className="btn accent">Add Contract</button></div></form></Modal>}
