'use client';
import { useMemo, useState } from 'react';
import { FileText, Folder, Receipt, Globe2, Pencil, Trash2 } from 'lucide-react';
import { useAppData } from './app-provider';
import { DeleteClientDialog, EditClientDialog } from './dialogs';
import { Client } from '@/lib/types';
const money=(n:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(n);
const badge=(s:string)=> s==='Completed'||s==='Paid'||s==='Signed'?'green':s==='In Progress'||s==='Building'?'blue':s==='Planning'||s==='Partial'||s==='Sent'?'yellow':s==='Overdue'?'red':'gray';
export function ClientsPage(){const {clients}=useAppData();const [q,setQ]=useState('');const [status,setStatus]=useState('All');const [editing,setEditing]=useState<Client|null>(null);const [deleting,setDeleting]=useState<Client|null>(null);const rows=useMemo(()=>clients.filter(c=>(status==='All'||c.status===status)&&`${c.name} ${c.business} ${c.email}`.toLowerCase().includes(q.toLowerCase())),[clients,q,status]);return <><Head title="Clients" text="Manage contacts, packages, project values and recurring fees."/><div className="filters"><input placeholder="Search clients..." value={q} onChange={e=>setQ(e.target.value)}/><select value={status} onChange={e=>setStatus(e.target.value)}><option>All</option><option>Lead</option><option>Demo</option><option>Contract Signed</option><option>Building</option><option>Completed</option><option>Maintenance</option></select></div><div className="table-wrap"><table className="data-table"><thead><tr><th>Business</th><th>Contact</th><th>Status</th><th>Package</th><th>Project Value</th><th>Recurring</th><th>Start</th><th>Actions</th></tr></thead><tbody>{rows.map(c=><tr key={c.id}><td><strong>{c.business}</strong><div className="muted">{c.website}</div></td><td>{c.name}<div className="muted">{c.email}</div></td><td><span className={`badge ${badge(c.status)}`}>{c.status}</span></td><td>{c.package}</td><td>{money(c.projectValue)}</td><td>{money(c.recurringFee)}/mo</td><td>{c.startDate}</td><td><div style={{display:'flex',gap:8}}><button className="icon-btn" title="Edit client" aria-label={`Edit ${c.business}`} onClick={()=>setEditing(c)}><Pencil size={16}/></button><button className="icon-btn" title="Delete client" aria-label={`Delete ${c.business}`} onClick={()=>setDeleting(c)}><Trash2 size={16}/></button></div></td></tr>)}</tbody></table></div>{editing&&<EditClientDialog client={editing} close={()=>setEditing(null)}/>} {deleting&&<DeleteClientDialog client={deleting} close={()=>setDeleting(null)}/>}</>}
export function ProjectsPage(){const {projects,clients}=useAppData();const [status,setStatus]=useState('All');const rows=projects.filter(p=>status==='All'||p.status===status);return <><Head title="Projects" text="Track each website build from planning through launch."/><div className="filters"><select value={status} onChange={e=>setStatus(e.target.value)}><option>All</option><option>Planning</option><option>In Progress</option><option>On Hold</option><option>Completed</option></select></div><div className="table-wrap"><table className="data-table"><thead><tr><th>Project</th><th>Client</th><th>Status</th><th>Price</th><th>Progress</th><th>Start</th><th>Target Launch</th></tr></thead><tbody>{rows.map(p=><tr key={p.id}><td><strong>{p.name}</strong><div className="muted">{p.type}</div></td><td>{clients.find(c=>c.id===p.clientId)?.business||'Deleted client'}</td><td><span className={`badge ${badge(p.status)}`}>{p.status}</span></td><td>{money(p.price)}</td><td><div style={{minWidth:130}}><div className="progress"><i style={{width:`${p.progress}%`}}/></div><div className="muted" style={{fontSize:11,marginTop:4}}>{p.progress}%</div></div></td><td>{p.startDate}</td><td>{p.targetLaunchDate}</td></tr>)}</tbody></table></div></>}
export function PaymentsPage(){const {payments,clients}=useAppData();const [status,setStatus]=useState('All');const rows=payments.filter(p=>status==='All'||p.status===status);return <><Head title="Payments" text="See invoices, payments received, balances and upcoming due dates."/><div className="filters"><select value={status} onChange={e=>setStatus(e.target.value)}><option>All</option><option>Paid</option><option>Unpaid</option><option>Partial</option><option>Overdue</option></select></div><div className="table-wrap"><table className="data-table"><thead><tr><th>Invoice</th><th>Client</th><th>Type</th><th>Charged</th><th>Paid</th><th>Due</th><th>Method</th><th>Status</th></tr></thead><tbody>{rows.map(p=><tr key={p.id}><td><strong>{p.invoice}</strong></td><td>{clients.find(c=>c.id===p.clientId)?.business||'Deleted client'}</td><td>{p.type}</td><td>{money(p.amountCharged)}</td><td>{money(p.amountPaid)}</td><td>{p.dueDate}</td><td>{p.method||'—'}</td><td><span className={`badge ${badge(p.status)}`}>{p.status}</span></td></tr>)}</tbody></table></div></>}
export function ContractsPage(){const {contracts,clients}=useAppData();return <><Head title="Contracts" text="Keep every client agreement organized in one place."/><div className="table-wrap"><table className="data-table"><thead><tr><th>Contract</th><th>Client</th><th>Signed Date</th><th>Status</th><th>File</th></tr></thead><tbody>{contracts.map(c=><tr key={c.id}><td><strong>{c.name}</strong></td><td>{clients.find(x=>x.id===c.clientId)?.business||'Deleted client'}</td><td>{c.signedDate||'Not signed'}</td><td><span className={`badge ${badge(c.status)}`}>{c.status}</span></td><td>{c.fileName}</td></tr>)}</tbody></table></div></>}
export function FilesPage(){const cards=[['Contracts',FileText,'Signed agreements and scope documents'],['Invoices',Receipt,'Invoices and payment records'],['Assets',Folder,'Logos, photos and client content'],['Website',Globe2,'Project references and launch files']] as const;return <><Head title="Files" text="A simple client-file workspace. Version 1 shows the structure before cloud storage is connected."/><div className="grid file-grid">{cards.map(([name,Icon,text])=><div className="file-card" key={name}><Icon size={24}/><h3>{name}</h3><div className="muted">{text}</div><div style={{marginTop:14}}><span className="badge gray">Mock records</span></div></div>)}</div></>}
function Head({title,text}:{title:string;text:string}){return <div className="page-head"><div><h1>{title}</h1><p>{text}</p></div></div>}
export function ReportsPage(){const {totalIncome,outstanding,recurring,clients,payments,projects}=useAppData();const paid=payments.filter(p=>p.status==='Paid').length, open=payments.length-paid;return <><Head title="Reports" text="A fast view of revenue, client growth and payment health."/><div className="grid report-grid"><Report title="Income received" value={money(totalIncome)} note="Across all recorded payments"/><Report title="Outstanding" value={money(outstanding)} note={`${open} invoices still open`}/><Report title="Recurring revenue" value={money(recurring)} note="Expected monthly hosting/maintenance"/><Report title="Clients" value={String(clients.length)} note="All tracked clients"/><Report title="Completed projects" value={String(projects.filter(p=>p.status==='Completed').length)} note="Projects at 100%"/><Report title="Paid invoices" value={String(paid)} note={`${payments.length} total invoices`}/></div><div className="panel" style={{marginTop:16}}><div className="panel-head"><h2>Payment Status Breakdown</h2></div><div className="list">{['Paid','Unpaid','Partial','Overdue'].map(s=><div className="list-row" key={s}><strong>{s}</strong><span className={`badge ${badge(s)}`}>{payments.filter(p=>p.status===s).length}</span></div>)}</div></div></>}
function Report({title,value,note}:{title:string;value:string;note:string}){return <div className="stat-card"><div className="stat-label">{title}</div><div className="stat-value">{value}</div><div className="muted" style={{fontSize:12,marginTop:6}}>{note}</div></div>}
export function SettingsPage(){const [saved,setSaved]=useState(false);return <><Head title="Settings" text="Set your business defaults for the tracker."/><div className="panel settings-card"><form onSubmit={e=>{e.preventDefault();setSaved(true)}}><label>Business name<input defaultValue="DesignedbyTD"/></label><label>Owner name<input defaultValue="Tai Do"/></label><label>Contact email<input type="email" defaultValue="taido097@gmail.com"/></label><label>Currency<select defaultValue="USD"><option>USD</option></select></label><label>Default recurring fee<input type="number" defaultValue="50"/></label><div className="muted" style={{fontSize:12}}>Version 1 settings are session-only and reset on refresh.</div><button className="btn accent" style={{width:'fit-content'}}>Save Settings</button>{saved&&<div className="badge green" style={{width:'fit-content'}}>Saved for this session</div>}</form></div></>}
