import { getCloudDb } from './cloud-db';
import { Client, Contract, Payment, Project } from './types';

const db=getCloudDb();
const dnull=(v?:string)=>v||null;
function nextDue(p:string,day:number){if(!p)return'';const [y,m]=p.split('-').map(Number),safe=Math.min(28,Math.max(1,day||1)),x=new Date(Date.UTC(y,m,safe));return `${x.getUTCFullYear()}-${String(x.getUTCMonth()+1).padStart(2,'0')}-${String(safe).padStart(2,'0')}`}
export function normalizeClient(c:Client):Client{const day=Math.min(28,Math.max(1,c.billingDay||1));return{...c,billingDay:day,nextDueDate:c.recurringFee>0&&c.paidThrough?nextDue(c.paidThrough,day):c.nextDueDate||''}}
export const clientFrom=(r:any):Client=>normalizeClient({id:r.id,name:r.name,business:r.business,email:r.email||'',phone:r.phone||'',website:r.website||'',status:r.status,startDate:r.start_date||'',launchDate:r.launch_date||'',package:r.package||'',projectValue:Number(r.project_value||0),recurringFee:Number(r.recurring_fee||0),billingDay:r.billing_day||1,paidThrough:r.paid_through||'',nextDueDate:r.next_due_date||'',notes:r.notes||''});
export const projectFrom=(r:any):Project=>({id:r.id,clientId:r.client_id||'',name:r.name,type:r.type||'',status:r.status,startDate:r.start_date||'',targetLaunchDate:r.target_launch_date||'',price:Number(r.price||0),progress:Number(r.progress||0),notes:r.notes||''});
export const paymentFrom=(r:any):Payment=>({id:r.id,clientId:r.client_id||'',invoice:r.invoice,type:r.type,amountCharged:Number(r.amount_charged||0),amountPaid:Number(r.amount_paid||0),paymentDate:r.payment_date||'',dueDate:r.due_date||'',method:r.method||'',status:r.status,coversThrough:r.covers_through||''});
export const contractFrom=(r:any):Contract=>({id:r.id,clientId:r.client_id||'',name:r.name,signedDate:r.signed_date||'',status:r.status,fileName:r.file_name||''});
export function clientRow(c:Client,uid:string){const n=normalizeClient(c);return{owner_id:uid,name:n.name,business:n.business,email:n.email,phone:n.phone,website:n.website,status:n.status,start_date:dnull(n.startDate),launch_date:dnull(n.launchDate),package:n.package,project_value:n.projectValue,recurring_fee:n.recurringFee,billing_day:n.billingDay||1,paid_through:dnull(n.paidThrough),next_due_date:dnull(n.nextDueDate),notes:n.notes}}
export function paymentRow(p:Payment,uid:string,cid?:string|null){return{owner_id:uid,client_id:cid===undefined?(p.clientId||null):cid,invoice:p.invoice,type:p.type,amount_charged:p.amountCharged,amount_paid:p.amountPaid,payment_date:dnull(p.paymentDate),due_date:dnull(p.dueDate),method:p.method,status:p.status,covers_through:dnull(p.coversThrough)}}
export async function fetchAll(){const [a,b,c,d]=await Promise.all([db.from('clients').select('*').order('created_at',{ascending:false}),db.from('projects').select('*').order('created_at',{ascending:false}),db.from('payments').select('*').order('created_at',{ascending:false}),db.from('contracts').select('*').order('created_at',{ascending:false})]);for(const q of[a,b,c,d])if(q.error)throw new Error(q.error.message);return{clients:(a.data||[]).map(clientFrom),projects:(b.data||[]).map(projectFrom),payments:(c.data||[]).map(paymentFrom),contracts:(d.data||[]).map(contractFrom)}}
export async function createClient(c:Client,uid:string){const q=await db.from('clients').insert(clientRow(c,uid)).select().single();if(q.error)throw new Error(q.error.message);return clientFrom(q.data)}
export async function saveClient(c:Client,uid:string){const q=await db.from('clients').update(clientRow(c,uid)).eq('id',c.id).select().single();if(q.error)throw new Error(q.error.message);return clientFrom(q.data)}
export async function removeRow(table:'clients'|'projects'|'payments',id:string){const q=await db.from(table).delete().eq('id',id);if(q.error)throw new Error(q.error.message)}
export async function createPayment(p:Payment,uid:string){const q=await db.from('payments').insert(paymentRow(p,uid)).select().single();if(q.error)throw new Error(q.error.message);return paymentFrom(q.data)}
export async function savePayment(p:Payment,uid:string){const q=await db.from('payments').update(paymentRow(p,uid)).eq('id',p.id).select().single();if(q.error)throw new Error(q.error.message);return paymentFrom(q.data)}
export async function createContract(c:Contract,uid:string){const q=await db.from('contracts').insert({owner_id:uid,client_id:c.clientId||null,name:c.name,signed_date:dnull(c.signedDate),status:c.status,file_name:c.fileName}).select().single();if(q.error)throw new Error(q.error.message);return contractFrom(q.data)}
export async function createHistory(c:Client,uid:string,existing:Payment[]){if(c.recurringFee<=0||!c.startDate||!c.paidThrough)return[];const s=new Date(`${c.startDate}T00:00:00Z`),e=new Date(`${c.paidThrough}T00:00:00Z`);if(s>e)return[];const invoices=new Set(existing.filter(x=>x.clientId===c.id).map(x=>x.invoice)),rows:any[]=[];let y=s.getUTCFullYear(),m=s.getUTCMonth();while(y<e.getUTCFullYear()||(y===e.getUTCFullYear()&&m<=e.getUTCMonth())){const ym=`${y}-${String(m+1).padStart(2,'0')}`,inv=`REC-${ym}-${c.id}`;if(!invoices.has(inv)){const day=Math.min(28,Math.max(1,c.billingDay||1)),date=`${ym}-${String(day).padStart(2,'0')}`;rows.push(paymentRow({id:'',clientId:c.id,invoice:inv,type:'Maintenance',amountCharged:c.recurringFee,amountPaid:c.recurringFee,paymentDate:date,dueDate:date,method:'Historical',status:'Paid',coversThrough:date},uid))}m++;if(m>11){m=0;y++}}if(!rows.length)return[];const q=await db.from('payments').insert(rows).select();if(q.error)throw new Error(q.error.message);return(q.data||[]).map(paymentFrom)}
export async function migrateLegacy(uid:string,raw:string){const s=JSON.parse(raw) as {clients?:Client[];projects?:Project[];payments?:Payment[];contracts?:Contract[]},map=new Map<string,string>();for(const c of s.clients||[]){const x=await createClient(c,uid);map.set(c.id,x.id)}for(const p of s.projects||[]){const q=await db.from('projects').insert({owner_id:uid,client_id:map.get(p.clientId)||null,name:p.name,type:p.type,status:p.status,start_date:dnull(p.startDate),target_launch_date:dnull(p.targetLaunchDate),price:p.price,progress:p.progress,notes:p.notes});if(q.error)throw new Error(q.error.message)}for(const p of s.payments||[]){const q=await db.from('payments').insert(paymentRow(p,uid,map.get(p.clientId)||null));if(q.error)throw new Error(q.error.message)}for(const c of s.contracts||[]){const q=await db.from('contracts').insert({owner_id:uid,client_id:map.get(c.clientId)||null,name:c.name,signed_date:dnull(c.signedDate),status:c.status,file_name:c.fileName});if(q.error)throw new Error(q.error.message)}}
